### ISSUE TITLE
Autopot - Skills not working when below HP/SP threshold and Potion on cooldown.

### ISSUE THREAD

**Issue by Navitron** [WillTheDoggy/Doggy-ToS-Addons#3]
So found a serious bug with the addon. At first I thought it was lag but it only happened when I was low HP. Guessing the addon keeps trying to use a potion even though it's on cooldown messing up other skill casts.

**Comment by WillTheDoggy** [comment]
Yup you are correct. I fixed it but haven't updated it here yet.

**Comment by WillTheDoggy** [comment]
Autopot is now banned. Closing this issue.

**Comment by Navitron** [comment]
Your Vacuum is now banned 
![81ll p3ehel _sl1500_](https://cloud.githubusercontent.com/assets/1194994/15975438/492cdbe0-2f02-11e6-8a6f-8510c7686ca3.jpg)

**Comment by ghost** [comment]
you stole my vacuum pic!

**Comment by Navitron** [comment]
I didn't steal your snowman though it's still safe. ⛄

**Comment by WillTheDoggy** [comment]
LMAO
